# inspiration from https://github.com/jerryryle/react-express-docker-skeleton

version: '3'
services:
  db:
    container_name: db
    build:
      context: ./backend/db/
    restart: unless-stopped
    env_file: ./backend/.env
    ports:
    - "3306:3306"
  api:
    container_name: api
    build:
      context: ./backend/
    restart: unless-stopped
    env_file: ./backend/.env
    environment:
      CHOKIDAR_USEPOLLING: "true"
      MYSQL_HOSTNAME: db
    volumes:
      - ./backend/:/backend
    links:
      - db
    depends_on:
      - db
    ports:
      - "9000:9000"
  ui:
    container_name: ui
    build:
      context: ./ui/
    restart: unless-stopped
    volumes:
      - ./ui/:/ui
    links:
      - api
    depends_on:
      - api
    ports:
      - "3000:3000"